name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: bazelbuild/setup-bazelisk@v1
      - run: sudo apt-get install libboost-all-dev libmysqlclient-dev libmysqlcppconn-dev redis -y
      - run: bazel test //services/authentication_service:random_generator_test
      - run: bazel test //services/authentication_service:redis_client_test
      - run: bazel test //services/authentication_service:login_test
      - run: bazel test //services/person_service:all
