name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - uses: bazelbuild/setup-bazelisk@v1
      - run: sudo apt-get install libboost-all-dev libmysqlclient-dev libmysqlcppconn-dev -y
      - run: bazel test //services/mysql_service:faculty_service_test
