name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "$HOME/.cache/bazel"
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel test //...
