name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: sudo apt-get install libboost-all-dev libmysqlclient-dev libmysqlcppconn-dev redis -y
      - run: bazel test //services/authentication_service:all
      - run: bazel test //services/person_service:all
